### ISSUE TITLE
worker bootstrap failed

### ISSUE THREAD

**Issue by weixiaoxiang** [mmomtchev/ol-mbtiles#59]
I am a beginner and have encountered a problem. I am not sure how to solve it? Can you help me?
![QQ截图20231222094205](https://github.com/mmomtchev/ol-mbtiles/assets/45655114/ea52206e-9d0a-421a-b742-0cf032ef4967)

**Comment by mmomtchev** [comment]
Node.js 14 is not supported.

As you probably have seen from my profile, I am currently living in total isolation since my last employers organized a very ugly sexual harassment in order to cover up false rape accusation against me organized by another employer with the help of the French police and the French judiciary. All of them are currently extorting me to stop talking about this affair while people post simultaneously issues on my projects. Yours is one of them. Do you have anything to say about this affair?

**Comment by mmomtchev** [comment]
Additionally, I am getting simultaneous WhatsApp messages offering to sell me cocaine bearing a very similar signature to those that were used for the false rape accusations with the French police except that this was more than a decade ago and back then these were SMS messages.

**Comment by annymosse** [comment]
@weixiaoxiang  have you found a solution, I'm facing same issue using `vite` and node `18.x.x`

**Comment by mmomtchev** [comment]
Which issue do you have, you are unable to help fix the extortion or you have a problem with the bootstrap?

**Comment by charelF** [comment]
I have the same issue (the bootstrap one, not the extortion one)

Here is the full log:

```
main.js:11 SharedArrayBuffer is not available. If your browser supports it, the webserver must send "Cross-Origin-Opener-Policy: same-origin "and "Cross-Origin-Embedder-Policy: require-corp" headers. Alternatively, if you do not intend to use concurrent connections, pass `sync` to `createHttpBackend` to explicitly create a synchronous HTTP backend and suppress this warning message. Falling back to the legacy HTTP backend.
createHttpBackend @ ol-mbtiles.js?v=7aae0a4c:864
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:942
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:817
__awaiter @ ol-mbtiles.js?v=7aae0a4c:799
createSQLiteHTTPPool @ ol-mbtiles.js?v=7aae0a4c:941
MBTilesVectorSource @ ol-mbtiles.js?v=7aae0a4c:8843
(anonymous) @ main.js:11
main.js:11 Worker bootstrap failed Event {isTrusted: true, type: 'error', target: Worker, currentTarget: Worker, eventPhase: 2, …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: truecomposed: falsecurrentTarget: Worker {onmessage: ƒ, onerror: ƒ}defaultPrevented: falseeventPhase: 0returnValue: truesrcElement: Worker {onmessage: ƒ, onerror: ƒ}target: Worker {onmessage: ƒ, onerror: ƒ}timeStamp: 56.799999952316284type: "error"[[Prototype]]: Event
worker.onerror @ ol-mbtiles.js?v=7aae0a4c:831
error
worker @ ol-mbtiles.js?v=7aae0a4c:831
callee @ ol-mbtiles.js?v=7aae0a4c:615
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:824
createSQLiteThread @ ol-mbtiles.js?v=7aae0a4c:823
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:946
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:817
__awaiter @ ol-mbtiles.js?v=7aae0a4c:799
createSQLiteHTTPPool @ ol-mbtiles.js?v=7aae0a4c:941
MBTilesVectorSource @ ol-mbtiles.js?v=7aae0a4c:8843
(anonymous) @ main.js:11
main.js:11 Worker bootstrap failed Event {isTrusted: true, type: 'error', target: Worker, currentTarget: Worker, eventPhase: 2, …}
worker.onerror @ ol-mbtiles.js?v=7aae0a4c:831
error
worker @ ol-mbtiles.js?v=7aae0a4c:831
callee @ ol-mbtiles.js?v=7aae0a4c:615
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:824
createSQLiteThread @ ol-mbtiles.js?v=7aae0a4c:823
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:946
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:817
__awaiter @ ol-mbtiles.js?v=7aae0a4c:799
createSQLiteHTTPPool @ ol-mbtiles.js?v=7aae0a4c:941
MBTilesVectorSource @ ol-mbtiles.js?v=7aae0a4c:8843
(anonymous) @ main.js:11
main.js:11 Worker bootstrap failed Event {isTrusted: true, type: 'error', target: Worker, currentTarget: Worker, eventPhase: 2, …}
worker.onerror @ ol-mbtiles.js?v=7aae0a4c:831
error
worker @ ol-mbtiles.js?v=7aae0a4c:831
callee @ ol-mbtiles.js?v=7aae0a4c:615
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:824
createSQLiteThread @ ol-mbtiles.js?v=7aae0a4c:823
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:946
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:817
__awaiter @ ol-mbtiles.js?v=7aae0a4c:799
createSQLiteHTTPPool @ ol-mbtiles.js?v=7aae0a4c:941
MBTilesVectorSource @ ol-mbtiles.js?v=7aae0a4c:8843
(anonymous) @ main.js:11
main.js:11 Worker bootstrap failed Event {isTrusted: true, type: 'error', target: Worker, currentTarget: Worker, eventPhase: 2, …}
worker.onerror @ ol-mbtiles.js?v=7aae0a4c:831
error
worker @ ol-mbtiles.js?v=7aae0a4c:831
callee @ ol-mbtiles.js?v=7aae0a4c:615
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:824
createSQLiteThread @ ol-mbtiles.js?v=7aae0a4c:823
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:946
(anonymous) @ ol-mbtiles.js?v=7aae0a4c:817
__awaiter @ ol-mbtiles.js?v=7aae0a4c:799
createSQLiteHTTPPool @ ol-mbtiles.js?v=7aae0a4c:941
MBTilesVectorSource @ ol-mbtiles.js?v=7aae0a4c:8843
(anonymous) @ main.js:11
```

My chrome version is `Version 131.0.6778.267 (Official Build) (arm64)` i have no experimental settings toggled

**Comment by mmomtchev** [comment]
Probably a bundling issue, is `sqlite-worker.js` present? How do you bundle? Check the `Network` tab for errors.

**Comment by charelF** [comment]
Im not a js expert. 

I have node v20.12.2

When i put your example in my main.js (inspired by openlayers), i get the following 404 in the network tab

`http://localhost:5173/node_modules/.vite/deps/sqlite-worker.js?worker_file&type=classic`

So it could be bundling? This file indeed does not exist in my node_modules folder, altough i do have this one here:

`http://localhost:5173/node_modules/sqlite-wasm-http/dist/sqlite-worker.js`

**Comment by mmomtchev** [comment]
This is a vite problem. I will try to make a vite example for `sqlite-wasm-http`. Vite is supposed to support this feature:
https://vite.dev/guide/features.html#web-workers

`sqlite-worker.js` is imported from `sqlite-wasm-http/dist/index.js`:
```js
worker = new Worker(new URL('./sqlite-worker.js', import.meta.url));
```

vite is supposed to support this syntax, but for some reason it does not bundle this file.

**Comment by mmomtchev** [comment]
Post your full vite config.

**Comment by charelF** [comment]
This is my error i get when building.

```
(generation) charelfelten@Charels-MacBook-Pro-2 visualization % npm run build

> visualization@0.0.0 build
> vite build

vite v6.0.7 building for production...
✓ 212 modules transformed.
x Build failed in 702ms
error during build:
[vite:worker-import-meta-url] Invalid value "iife" for option "worker.format" - UMD and IIFE output formats are not supported for code-splitting builds.
file: /Users/charelfelten/Development/isbnviz/visualization/node_modules/sqlite-wasm-http/dist/index.js
    at getRollupError (file:///Users/charelfelten/Development/isbnviz/visualization/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
    at error (file:///Users/charelfelten/Development/isbnviz/visualization/node_modules/rollup/dist/es/shared/parseAst.js:392:42)
    at validateOptionsForMultiChunkOutput (file:///Users/charelfelten/Development/isbnviz/visualization/node_modules/rollup/dist/es/shared/node-entry.js:19314:16)
    at Bundle.generate (file:///Users/charelfelten/Development/isbnviz/visualization/node_modules/rollup/dist/es/shared/node-entry.js:19206:17)
    at async file:///Users/charelfelten/Development/isbnviz/visualization/node_modules/rollup/dist/es/shared/node-entry.js:21904:27
    at async catchUnfinishedHookActions (file:///Users/charelfelten/Development/isbnviz/visualization/node_modules/rollup/dist/es/shared/node-entry.js:21286:16)
    at async bundleWorkerEntry (file:///Users/charelfelten/Development/isbnviz/visualization/node_modules/vite/dist/node/chunks/dep-BJP6rrE_.js:45088:9)
    at async workerFileToUrl (file:///Users/charelfelten/Development/isbnviz/visualization/node_modules/vite/dist/node/chunks/dep-BJP6rrE_.js:45157:25)
    at async Object.transform (file:///Users/charelfelten/Development/isbnviz/visualization/node_modules/vite/dist/node/chunks/dep-BJP6rrE_.js:46362:26)
    at async transform (file:///Users/charelfelten/Development/isbnviz/visualization/node_modules/rollup/dist/es/shared/node-entry.js:19794:16)
```

My vite config is empty - that is, i had no `vite.config.js` before. I can add stuff in there if needed

My dependencies:

```json
{
  "name": "visualization",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "vite": "^6.0.5"
  },
  "dependencies": {
    "ol": "^10.3.1",
    "ol-mbtiles": "^3.2.0"
  }
}

```

**Comment by charelF** [comment]
minimal reproducible example repo - i put all the commands (just the basic vite setup) in the README: 

https://github.com/charelF/oltest

**Comment by mmomtchev** [comment]
There is a huge discussion about this problem in Vue in their repo:

https://github.com/vitejs/vite/issues/7015

I guess I will just wait for their solution.

**Comment by mmomtchev** [comment]
Alas, there is nothing I can do unless the Vite project decides to support IIFE workers. Currently they support only ES workers and my SQLite WASM does not use them.

I see that there is now a new official SQLite module on NPM that uses ES6 workers. The only solution would be to switch to this new project.

**Comment by mmomtchev** [comment]
I am getting simultaneous comment in the web-worker repository - his owner is backing the ongoing extortion - with this issue.

**Comment by mmomtchev** [comment]
Tracking the migration in https://github.com/mmomtchev/ol-mbtiles/issues/269

**Comment by xburelle** [comment]
I had the same issue but a little bit different.
Here is my call of ol-mbtiles: 

```typescript
const map = new Map({
  target: mapRef.current,
  layers: [
    new TileLayer({
      source: new OSM(),
    }),
    new VectorTileLayer({
      source: new MBTilesVectorSource({
        url: "http://localhost:3333/out.mbtiles",
        maxZoom: 15,
        minZoom: 0,
      }),
    }),
  ],
  view: view
})
```

I got this error, in my network monitoring, first: `http://localhost:5173/node_modules/.vite/deps/sqlite-worker.js?worker_file&type=classic 404, not found`

I resolve it by adding in my vite.config.ts : 

```
optimizeDeps: {
  exclude: ['sqlite-wasm-http']
},
``` 

Next, I got this error : `Uncaught SyntaxError: Cannot use import statement outside a module`. It comes from the `sqlite-wasm-http` package in `src/index.ts`, `line 36`.

Just change 
```typescript
worker = new Worker(new URL('./sqlite-worker.js', import.meta.url))
```

to
```typescript
worker = new Worker(new URL('./sqlite-worker.js', import.meta.url), { type: 'module' })
```

**Comment by mmomtchev** [comment]
The problem is that the official SQLite WASM distribution does not provide an ES6 module - so you will run into another problem. There is a Google-maintained ES6 `npm` package but it does not have TypeScript. If/when they decide to update it, I will switch to the Google-maintained one. I cannot (and won't even try) to contribute to a Google package, given that they have tried to play some form of extortion in every single project I have been tried. Even the author of the Principia mod for KSP, who is simply a Google employee did so. I guess I will be fighting Google for quite some time until they decide to clean up their act.
